name: ${project.artifactId}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
dev-url: ${project.url}
authors: [Koanga, Diemex]
softdepend: [Vault]
commands:
    tm:
       description: Basic "master" command for TradeMod. Type /tm help for more info.
       usage: /tm [argument] *
permissions:
    trademod.cantrade:
        description: If a player does not have this permission, or if it's set to false, they cannot trade nor use any commands.
        default: true
    trademod.currency:
        description: If a player does not have this permission, or if it's set to false, they cannot use currency commands.
        default: true
    trademod.quickreopen:
        description: If a player does not have this permission, or if it's set to false, they cannot right click to reopen the trade window.
        default: true
    trademod.rightclickrequest:
        description: If a player does not have this permission, or if it's set to false, they cannot right click, while sneaking, to request a player to trade.
        default: true